# Generated by Django 5.2.8 on 2025-11-15 22:35

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('storage_quota', models.BigIntegerField(default=5368709120, help_text='Total storage quota in bytes')),
                ('storage_used', models.BigIntegerField(default=0, help_text='Current storage used in bytes')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='storage_users', related_query_name='storage_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='storage_users', related_query_name='storage_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileSearchStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Unique store name', max_length=255, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable display name', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_files', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('storage_size_bytes', models.BigIntegerField(default=0, help_text='Actual file storage size')),
                ('embeddings_size_bytes', models.BigIntegerField(default=0, help_text='Estimated embeddings storage size (~3x)')),
                ('chunking_strategy', models.CharField(choices=[('auto', 'Auto'), ('whitespace', 'Whitespace'), ('semantic', 'Semantic'), ('fixed', 'Fixed Size')], default='auto', help_text='Default chunking strategy for files in this store', max_length=50)),
                ('max_tokens_per_chunk', models.IntegerField(default=512, help_text='Maximum tokens per chunk', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2048)])),
                ('max_overlap_tokens', models.IntegerField(default=50, help_text='Overlap between consecutive chunks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('storage_quota', models.BigIntegerField(default=1073741824, help_text='Storage quota in bytes')),
                ('custom_metadata', models.JSONField(blank=True, default=dict, help_text='Store-level metadata')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Owner of this file search store', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_search_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JSONDataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('database_type', models.CharField(choices=[('SQL', 'PostgreSQL'), ('NoSQL', 'MongoDB')], max_length=10)),
                ('confidence_score', models.IntegerField(help_text='AI confidence in DB choice (0-100)')),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inferred_schema', models.JSONField(default=dict)),
                ('sample_data', models.JSONField(blank=True, default=dict)),
                ('structure_depth', models.IntegerField(default=0)),
                ('has_nested_objects', models.BooleanField(default=False)),
                ('has_arrays', models.BooleanField(default=False)),
                ('is_consistent', models.BooleanField(default=True)),
                ('ai_reasoning', models.TextField(blank=True, null=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Owner of this JSON data store', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='json_data_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('detected_type', models.CharField(help_text='Primary file category', max_length=50)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_extension', models.CharField(max_length=20)),
                ('magic_description', models.TextField(blank=True, null=True)),
                ('ai_category', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_tags', models.JSONField(blank=True, default=list)),
                ('ai_description', models.TextField(blank=True, null=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('storage_category', models.CharField(max_length=100)),
                ('storage_subcategory', models.CharField(max_length=100)),
                ('relative_path', models.CharField(max_length=1024)),
                ('custom_metadata', models.JSONField(blank=True, default=dict, help_text='Custom key-value metadata for filtering searches')),
                ('is_indexed', models.BooleanField(default=False, help_text='Whether file has been indexed for search')),
                ('indexed_at', models.DateTimeField(blank=True, help_text='When file was indexed', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete - moved to trash')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When file was moved to trash', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('file_search_store', models.ForeignKey(blank=True, help_text='Optional file search store for organized document management', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='storage.filesearchstore')),
                ('user', models.ForeignKey(blank=True, help_text='Owner of this media file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='Position of this chunk in the document')),
                ('chunk_text', models.TextField(help_text='The actual text content of this chunk')),
                ('chunk_size', models.IntegerField(help_text='Number of characters in this chunk')),
                ('token_count', models.IntegerField(default=0, help_text='Estimated token count for this chunk')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, help_text='Vector embedding generated by Ollama nomic-embed-text model')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_type', models.CharField(help_text='File type/category', max_length=50)),
                ('page_number', models.IntegerField(blank=True, help_text='Page number (for PDFs)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (author, date, tags, etc.)')),
                ('chunking_strategy', models.CharField(default='auto', max_length=50)),
                ('overlap_tokens', models.IntegerField(default=0, help_text='Overlap with previous chunk')),
                ('citation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('source_reference', models.CharField(blank=True, help_text="Human-readable source reference (e.g., 'report.pdf, page 5, para 3')", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_search_store', models.ForeignKey(blank=True, help_text='File search store this chunk belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='storage.filesearchstore')),
                ('media_file', models.ForeignKey(blank=True, help_text='Reference to the source media file (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='storage.mediafile')),
            ],
            options={
                'ordering': ['media_file', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='The search query')),
                ('query_embedding', pgvector.django.vector.VectorField(dimensions=768, help_text='Vector embedding of the query')),
                ('results_count', models.IntegerField(default=0)),
                ('top_result_score', models.FloatField(blank=True, null=True)),
                ('metadata_filter', models.JSONField(blank=True, default=dict, help_text='Metadata filter applied to search')),
                ('user_session', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_search_stores', models.ManyToManyField(blank=True, help_text='Stores searched (if filtered)', to='storage.filesearchstore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text='Generated response text')),
                ('grounding_score', models.FloatField(blank=True, help_text='Confidence score for grounding (0-1)', null=True)),
                ('citations', models.JSONField(default=list, help_text='Structured citation data with chunk references')),
                ('retrieval_time_ms', models.IntegerField(blank=True, null=True)),
                ('generation_time_ms', models.IntegerField(blank=True, null=True)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_chunks', models.ManyToManyField(help_text='Document chunks used to generate this response', related_name='rag_responses', to='storage.documentchunk')),
                ('search_query', models.ForeignKey(help_text='Original search query', on_delete=django.db.models.deletion.CASCADE, related_name='rag_responses', to='storage.searchquery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='storage_use_email_cbb2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='storage_use_usernam_262e51_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_id'], name='storage_use_user_id_9a5e30_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='storage_use_is_acti_68be0c_idx'),
        ),
        migrations.AddIndex(
            model_name='filesearchstore',
            index=models.Index(fields=['name'], name='storage_fil_name_235ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='filesearchstore',
            index=models.Index(fields=['store_id'], name='storage_fil_store_i_1c9245_idx'),
        ),
        migrations.AddIndex(
            model_name='filesearchstore',
            index=models.Index(fields=['is_active'], name='storage_fil_is_acti_c92cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='jsondatastore',
            index=models.Index(fields=['database_type'], name='storage_jso_databas_718e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='jsondatastore',
            index=models.Index(fields=['created_at'], name='storage_jso_created_25128b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['detected_type'], name='storage_med_detecte_92252d_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['storage_category'], name='storage_med_storage_e98a92_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_at'], name='storage_med_uploade_cd3334_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['is_deleted'], name='storage_med_is_dele_0be7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['deleted_at'], name='storage_med_deleted_83ec16_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['file_name'], name='storage_doc_file_na_d694ab_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['file_type'], name='storage_doc_file_ty_aeeaaa_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['created_at'], name='storage_doc_created_b339f4_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['created_at'], name='storage_sea_created_c6c709_idx'),
        ),
        migrations.AddIndex(
            model_name='ragresponse',
            index=models.Index(fields=['created_at'], name='storage_rag_created_89592a_idx'),
        ),
        migrations.AddIndex(
            model_name='ragresponse',
            index=models.Index(fields=['grounding_score'], name='storage_rag_groundi_d564a6_idx'),
        ),
    ]
