# Generated by Django 5.2.8 on 2025-11-16 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondatastore',
            name='schema_file',
            field=models.ForeignKey(blank=True, help_text='Generated schema file accessible in file browser', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='json_schemas', to='storage.mediafile'),
        ),
    ]
