# Generated by Django 5.2.8 on 2025-11-15 12:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_searchquery_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='chunking_strategy',
            field=models.CharField(default='auto', max_length=50),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='citation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='overlap_tokens',
            field=models.IntegerField(default=0, help_text='Overlap with previous chunk'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='source_reference',
            field=models.CharField(blank=True, help_text="Human-readable source reference (e.g., 'report.pdf, page 5, para 3')", max_length=500),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='token_count',
            field=models.IntegerField(default=0, help_text='Estimated token count for this chunk'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='custom_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Custom key-value metadata for filtering searches'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='indexed_at',
            field=models.DateTimeField(blank=True, help_text='When file was indexed', null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='is_indexed',
            field=models.BooleanField(default=False, help_text='Whether file has been indexed for search'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='metadata_filter',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata filter applied to search'),
        ),
        migrations.CreateModel(
            name='FileSearchStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Unique store name', max_length=255, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable display name', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_files', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('storage_size_bytes', models.BigIntegerField(default=0, help_text='Actual file storage size')),
                ('embeddings_size_bytes', models.BigIntegerField(default=0, help_text='Estimated embeddings storage size (~3x)')),
                ('chunking_strategy', models.CharField(choices=[('auto', 'Auto'), ('whitespace', 'Whitespace'), ('semantic', 'Semantic'), ('fixed', 'Fixed Size')], default='auto', help_text='Default chunking strategy for files in this store', max_length=50)),
                ('max_tokens_per_chunk', models.IntegerField(default=512, help_text='Maximum tokens per chunk', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2048)])),
                ('max_overlap_tokens', models.IntegerField(default=50, help_text='Overlap between consecutive chunks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('storage_quota', models.BigIntegerField(default=1073741824, help_text='Storage quota in bytes')),
                ('custom_metadata', models.JSONField(blank=True, default=dict, help_text='Store-level metadata')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='storage_fil_name_235ff2_idx'), models.Index(fields=['store_id'], name='storage_fil_store_i_1c9245_idx'), models.Index(fields=['is_active'], name='storage_fil_is_acti_c92cd2_idx')],
            },
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='file_search_store',
            field=models.ForeignKey(blank=True, help_text='File search store this chunk belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='storage.filesearchstore'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file_search_store',
            field=models.ForeignKey(blank=True, help_text='Optional file search store for organized document management', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='storage.filesearchstore'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='file_search_stores',
            field=models.ManyToManyField(blank=True, help_text='Stores searched (if filtered)', to='storage.filesearchstore'),
        ),
        migrations.CreateModel(
            name='RAGResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text='Generated response text')),
                ('grounding_score', models.FloatField(blank=True, help_text='Confidence score for grounding (0-1)', null=True)),
                ('citations', models.JSONField(default=list, help_text='Structured citation data with chunk references')),
                ('retrieval_time_ms', models.IntegerField(blank=True, null=True)),
                ('generation_time_ms', models.IntegerField(blank=True, null=True)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.ForeignKey(help_text='Original search query', on_delete=django.db.models.deletion.CASCADE, related_name='rag_responses', to='storage.searchquery')),
                ('source_chunks', models.ManyToManyField(help_text='Document chunks used to generate this response', related_name='rag_responses', to='storage.documentchunk')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='storage_rag_created_89592a_idx'), models.Index(fields=['grounding_score'], name='storage_rag_groundi_d564a6_idx')],
            },
        ),
    ]
