# Generated by Django 5.2.8 on 2025-11-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_jsondatastore_schema_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='full_text',
            field=models.TextField(blank=True, help_text='Complete extracted text content from the document (stored for full retrieval)', null=True),
        ),
    ]
