# Generated by Django 5.2.8 on 2025-11-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_unified_json_storage'),
        ('storage', '0004_add_trash_bin'),
    ]

    operations = [
    ]
